export const code_type_service="Dịch Vụ Viễn Thông"
export const addSucc="Thêm mới thành công"
export const addError="Thêm mới thất bại, vui lòng kiểm tra lại"
export const updateSucc="Cập nhật thông tin thành công"
export const updateError="Cập nhật thông tin thất bại, vui lòng kiểm tra lại"